[package]
name = "Find_satoshi_key"
version = "0.0.6"
edition = "2021"

build = "build.rs"

[dependencies]
rand = "0.8.5"
bitcoin = "0.30.1"

num_cpus = "1.13.0"
tokio = { version = "1.20.1", features = ["full"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"